spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inscription_db
    username: postgres
    password: slim123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true

